### ISSUE TITLE
Bug: Getting unknown property: naffiq\bridge\BridgeModule::languageSwitchAction

### ISSUE THREAD

**Issue by altynbek07** [yii2-bridge/core#2]
@naffiq После первоначальной настройки модуля Bridge, зашел по адресу http://mysite.test/admin, и появилась ошибка связанные с переключением языка.
![unknown property yii base unknownpropertyexception 2018-06-28 18-34-44](https://user-images.githubusercontent.com/20629188/42034470-f4c231b0-7b01-11e8-8a34-7b1e6e05e8fc.png)

**Comment by naffiq** [comment]
👍
