### ISSUE TITLE
Bug: The view file does not exist

### ISSUE THREAD

**Issue by altynbek07** [yii2-bridge/core#3]
@naffiq На странице авторизации админки (http://mysite.test/admin/default/login), появляется ошибка: `The view file does not exist: /Users/rocketscientist/rocketdev/basic/vendor/naffiq/yii2-bridge/src/views/layouts/main.php`
![view not found yii base viewnotfoundexception 2018-06-28 18-35-47](https://user-images.githubusercontent.com/20629188/42034573-4b599a22-7b02-11e8-8579-2542d2fc42b9.png)

**Comment by naffiq** [comment]
👍
