### ISSUE TITLE
Mysql: Invalid default value for 'created_at'

### ISSUE THREAD

**Issue by Slayvin** [yii2-bridge/core#44]
I just got this error when running migrations on the production server:
```
*** applying m180424_121052_create_meta_tags_table
    > create table meta_tags ...Error: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'
The SQL being executed was: CREATE TABLE `meta_tags` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `created_at` datetime DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата создания',
        `updated_at` datetime DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата редактирования'
)

```
On that server, Mysql version is 5.5.60-MariaDB - MariaDB Server

Similar issue found on SO:
https://stackoverflow.com/questions/9005766/invalid-default-value-for-dateadded

**Comment by altynbek07** [comment]
@Slayvin i have install mysql 5.5 and fixed this bug #46

**Comment by naffiq** [comment]
@Slayvin #46 was merged, can I ask you to confirm that the bug is resolved as well?

**Comment by Slayvin** [comment]
It is! Perfect, thanks!
