### ISSUE TITLE
Message file not found when adding new language

### ISSUE THREAD

**Issue by Slayvin** [yii2-bridge/core#48]
I get this message when I add a new language to my application: 

> The message file for category 'bridge' does not exist: ...\vendor/yii2-bridge/core/src/translations/fr/bridge.php
           

Because the module bootstrap method will register translations: https://github.com/yii2-bridge/core/blob/9a7b810906ad9838fd36b616bda708365b3972c6/src/BridgeModule.php#L175
then register the usuario module:  https://github.com/yii2-bridge/core/blob/9a7b810906ad9838fd36b616bda708365b3972c6/src/BridgeModule.php#L211
but both are private methods, so it's not possible to customize/override those methods.

The problem appears in the `registerUsuario `method:
https://github.com/yii2-bridge/core/blob/9a7b810906ad9838fd36b616bda708365b3972c6/src/BridgeModule.php#L358

What is the preferred solution to add new translations files ?
I mean, I could add the  missing message source in vendor files, but we shouldn't ever modify vendor files for obvious reasons. 

Would it be a problem to change the visibility of the `registerTranslations` method from _private_ to _protected_ ? At least then it would allow some customization.  

Or is there another way to add translations that I've completely missed ?

**Comment by Slayvin** [comment]
I'd be glad to submit a fix, but I'd like to know what you guys think ! 😉

**Comment by naffiq** [comment]
@Slayvin 
> Would it be a problem to change the visibility of the registerTranslations method from private to protected ? At least then it would allow some customization.

I think that's a decent solution to the problem you have, it would be great if you create a PR 👍

**Comment by Slayvin** [comment]
See #50

**Comment by naffiq** [comment]
@Slayvin great, I'll create new release soon 🎊

**Comment by naffiq** [comment]
https://github.com/yii2-bridge/core/releases/tag/v0.3.1
